name: Deploy Serverless AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run tests and generate coverage
        run: npm run test:cov

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=victor-repo
            -Dsonar.projectKey=VictorlBueno_challenge-auth
            -Dsonar.sources=src
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  deploy:
    needs: sonarqube
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checar repositório
        uses: actions/checkout@v2

      - name: Configura Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instala dependências
        run: npm install --legacy-peer-deps

      - name: Instala NestJS CLI globalmente
        run: npm install -g @nestjs/cli

      - name: Constrói o projeto com NestJS
        run: nest build

      - name: Configura AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy com Serverless Framework
        run: npx serverless deploy
